### ISSUE TITLE
Setup the project

### ISSUE THREAD

**Issue by 1ambda** [ZEPL/zeppelin-launcher#1]
1. Do we need UI framework even for an electron app? If it's true what should we use?
2. Let's use an electron boilerplate.

**Comment by 1ambda** [comment]
help wanted! @sravan-s

**Comment by sravan-s** [comment]
https://github.com/SimulatedGREG/electron-vue looks interesting

**Comment by 1ambda** [comment]
handled in https://github.com/ZEPL/zeppelin-launcher/commit/8b45878df42d084484e7600fb09ca9fd7de7fae4
